### ISSUE TITLE
We have a wiki for Astro Hack Week 2015! It's almost ready to publicize, just needs some logistical details

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#1]
Hi all!

I just adapted last year's Astro Hack Week wiki into this year's, and started a new hackpad collection for us to use. It's almost ready to be emailed to the participants to get them started thinking about hacks, but first I think some of the logistics details need fixing. 

@dhuppenkothen can you please do some browsing of this site, starting from the README at https://github.com/AstroHackWeek/AstroHackWeek2015 , and fill in whatever missing details you can, please?

Cheers

Phil

**Comment by dhuppenkothen** [comment]
Hi Phil,
I added information, maps and programme! Anything I missed out on?

**Comment by drphilmarshall** [comment]
Looks great! Ready to ship :-)
