### ISSUE TITLE
Email to hackers, to get them started

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#2]
I'll dig out last year's, edit and for comment before @dhuppenkothen or I sends it out.

**Comment by drphilmarshall** [comment]
OK, here we are - please edit as you see fit [on this issue thread](https://github.com/AstroHackWeek/AstroHackWeek2015/issues/2). I can't remember the NYU room details... @dhuppenkothen do you have a group email list for the participants? Last year we used astrohackweek2014@googlegroups.com 

Given the "sent" date it looks like we are ahead of the game this year! :-)

---

Dear Hackers,

There's almost no time before #AstroHackWeek starts, which means ​that ​now is the perfect time to think about what you are going to hack on in the afternoons next week. 

Here's the plan: https://github.com/AstroHackWeek/AstroHackWeek2015/wiki/Hacking-Central

Here are a couple of suggestions:
- Email or tweet at some people you want to hack with. Ask them questions about the ideas they've posted to the index at https://hackpad.com/Astro-Hack-Week-2015-Hack-Index-RLfELNMgCSC
- If you have an idea for a hack, add it to this index. If you have a project that you _know_ you're going to work on, make a hackpad for it as well, and add a few notes about your idea. This'll help you pitch it to the rest of the group on Monday.
- Hacking will kick-off at noon on Monday, at the end of the first morning's tutorial sessions, in room 905/907 at the Kimmel Center for University Life (see the Wiki for room details, maps and directions), just before lunch​. You'll each have 30 seconds (count them!) to say who you are and what you'd like to work on, referring to the index page which we'll have open, before we disperse.

Do feel free to reply-all to this message with​ ​questions/comments/excitement etc - or do likewise on twitter with the hashtag #AstroHackWeek. The sooner we start talking to each other​ ​the better!

Looking forward to hanging out ​with you ​next week :-)

Cheers

Phil and Daniela

**Comment by dhuppenkothen** [comment]
Hi Phil, I updated your comment with the room number and location. One comment on the e-mail: do you think it will be confusing that we say "hacking will kick off at noon Monday"? I feel like this might imply to some people, who don't read carefully and don't look at the Wiki that there's no morning session that day! In that spirit, I've edited that sentence a bit, too.

**Comment by drphilmarshall** [comment]
Good point. I tweaked it too. It's ready for you to to send! :-)
