### ISSUE TITLE
Reorganize

### ISSUE THREAD

**Issue by kbarbary** [AstroHackWeek/AstroHackWeek2015#21]
The repo got a bit messy during the week, so I'm going to reorganize it as such:
- `day1-data-exporation`
- `day2-big-data`
- `day3-machine-learning`
- `day4-day5-inference`
- `breakouts/...`
- `hacks/...`

Before I do, wanted to know what the status of the `bayes-cv` branch is. I assume it should be merged into master? I can move the CV part that was a hack into `hacks`. @drphilmarshall @eggplantbren

**Comment by drphilmarshall** [comment]
Yes - please do move the CV stuff into hacks, and don't merge with master.
Really Joao and I should start a separate repo for that project.

**Comment by kbarbary** [comment]
OK, I did move it to hacks but I also accidentally merged into master and then deleted the bayes-cv branch. (I was confused why we'd want to move it around but not merge). Do what you will from here (delete the file, clean from repo, etc). Don't think it makes sense to keep around an extra branch though.

Closing...
