### ISSUE TITLE
update web pages to AstroHackWeek 2016

### ISSUE THREAD

**Issue by davidwhogg** [AstroHackWeek/AstroHackWeek2015#23]
- move content on 2015 out to a list of "past events" which should also have 2014 link.
- make bare-bones content for 2016

**Comment by kbarbary** [comment]
Will do.

**Comment by kbarbary** [comment]
Done. http://astrohackweek.github.io/ (I'm usually not a fan of animated backgrounds - open to changing that.)

**Comment by drphilmarshall** [comment]
Sweet! Thanks Kyle.
