### ISSUE TITLE
when is AstroHackWeek2016 happening

### ISSUE THREAD

**Issue by davidwhogg** [AstroHackWeek/AstroHackWeek2015#24]
we need to choose dates _now_

**Comment by kbarbary** [comment]
Depends on _where_ as well, for room availability.
- Berkeley campus: semester starts 17 Aug 2016, instruction starts 24 Aug 2016 (last summer session ends Friday 12 Aug 2016).
- Stanford campus: instruction starts 26 Sep 2016 (I've heard campus is pretty empty for a few weeks between the end of summer programs and the start of the semester)

**Comment by kbarbary** [comment]
Closing this and moving discussion to https://github.com/AstroHackWeek/AstroHackWeek2016/issues/1

Continue discussion there.
