### ISSUE TITLE
Faux pas! LSSTC not listed on the sponsors webpage

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#26]
We need to fix this, even retrospectively!

**Comment by dhuppenkothen** [comment]
It was! I added it before Astro Hack Week!
Let me see what happened to that code!

**Comment by kbarbary** [comment]
Don't forget to update your remote to AstroHackWeek/2015.git since I moved the repo.

**Comment by kbarbary** [comment]
(and renamed the `master` branch to `gh-pages`).

**Comment by kbarbary** [comment]
Daniela fixed it. I messed something up when moving the repos around on Saturday, so the logo was only missing for the last four days.
