### ISSUE TITLE
Starter Hacks!

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#3]
@davidwhogg @dhuppenkothen @kbarbary 
Can you please think of a hack or two that either you plan to work on, or think might make a good AHW project, and then post it to the Astro Hack Week 2015 Hack Index here:

https://hackpad.com/Astro-Hack-Week-2015-Hack-Index-RLfELNMgCSC

Thanks!

**Comment by kbarbary** [comment]
Added one. I'll think on it some more, but will be offline the next few days.

**Comment by dhuppenkothen** [comment]
Added a hack, too. I might add another one or two in the next couple of weeks.

**Comment by drphilmarshall** [comment]
Alright! We are up to 5 hacks now, enough to be getting on with (although it would be good to have a few more _astronomy_ related ones - mea culpa). @davidwhogg what would you like to work on / advise on / support during Astro Hack Week? @eggplantbren? @amueller ? 

https://hackpad.com/Astro-Hack-Week-2015-Hack-Index-RLfELNMgCSC

**Comment by drphilmarshall** [comment]
PS. @amueller I just posted a hack idea in which I say that "machine
learning methods may help here" - feel free to join in! I want (someone) to
infer parameters M\* and z from data m, c1, c2, c3, c4 and s given a large
volume of (noisy) training data. It's the photometric redshift problem but
more interesting :-)

**Comment by drphilmarshall** [comment]
I think the hackpad is ticking along nicely - thanks for the starter suggestions, all!
