### ISSUE TITLE
Sunday night meetup?

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#4]
This was cool last year. I'll try and get to NY in time to join, and will need beer and company. Where shall we go? Answers on [this postcard](https://github.com/AstroHackWeek/AstroHackWeek2015/wiki/Evening-Outing-Ideas) please! :-)

**Comment by kbarbary** [comment]
My flight gets in at 3:45pm, so I'll be there! ...Wherever _there_ is.

**Comment by dhuppenkothen** [comment]
Yes! Good idea; I'd completely forgotten about this! I will think of places to go, but @davidwhogg is probably better qualified than me to make suggestions.
