### ISSUE TITLE
Schedule on website is out of date

### ISSUE THREAD

**Issue by drphilmarshall** [AstroHackWeek/AstroHackWeek2015#5]
I think we need to update it to match [the wiki](https://github.com/AstroHackWeek/AstroHackWeek2015/wiki/Programme).

**Comment by kbarbary** [comment]
Moved day 4, 5 to day 2, 3 in [this commit](https://github.com/AstroHackWeek/astrohackweek.github.io/commit/01099ad8da2723525f4c5728dcc1a679d91ee1dd).

**Comment by kbarbary** [comment]
Should we put the full detailed schedule up?

**Comment by drphilmarshall** [comment]
I'd say no, but a link to the programme page on the wiki is probably a good
idea! Thanks Kyle :-)

**Comment by kbarbary** [comment]
Added said link, and also a favicon, because procrastination.

Closing this...
